import type { Metadata } from 'next';
import { Commissioner } from 'next/font/google';
import './globals.css';
import Header from '@/components/sections/Header';
import Footer from '@/components/Footer';

const comm = Commissioner({
	variable: '--font-geist-sans',
	subsets: ['latin'],
	weight: ['100', '200', '300', '400'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" style={{ scrollBehavior: 'smooth' }}>
			<body className={`${comm.variable} antialiased`}>
				<div className="">
					{children}
				
				</div>
			</body>
		</html>
	);
}
